services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80

    volumes:
        - ./webpage/:/var/www/html/

  php:
    build: ./webpage/
    expose:
      - 9000
    volumes:
      - ./webpage/:/var/www/html/

  db:
    build: ./db/
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/:/var/lib/mysql


volumes:
  mysql:
